

def log_exception(message, exception):
    print(message, str(exception))
